name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:


jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      # setup-lisp requires an env variable to be set, not matrix.lisp
      - name: Set LISP env var
        run: echo "LISP=${{ matrix.lisp }}" >> $GITHUB_ENV
      # This action installs roswell and a few other utilities such as qlot
      - uses: 40ants/setup-lisp@v2

      # These steps run our tests
      - name: Run tests (Non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ros install neil-lindquist/ci-utils # for run-fiveam
          #ros install prove # for run-prove:
          #ros install rove # for [run-] rove

          # Run the tests
          run-fiveam -e t -l web-lisp/tests :web-lisp-tests
          run-prove web-lisp.asd
          rove web-lisp.asd
      