name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:


jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set LISP env var
        run: echo "LISP=${{ matrix.lisp }}" >> $GITHUB_ENV
      - uses: 40ants/setup-lisp@v2

      # These steps run our tests
      - name: Run tests
        shell: bash
        run: |
          # ros install neil-lindquist/ci-utils # for run-fiveam
          ros install sbcl-bin
          # Run the tests
          ros run --noinform --non-interactive  --load web-lisp.asd \
            --eval "(setf *compile-verbose* nil)" \
            --eval "(with-open-file (*error-output* \"warnings.log\" :direction :output :if-exists :supersede) (asdf:load-system :web-lisp/tests))" \
            --eval "(web-lisp-tests:run-tests)" 
