name: 'CI'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
          
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v4
        with:
          asdf-system: web-lisp
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: web-lisp